### ISSUE TITLE
Add card hover effect

### ISSUE THREAD

**Issue by BidyasagarAnupam** [BidyasagarAnupam/YearBook#92]
Add card hover effect

**Comment by CoderRedwing** [comment]
can i work on it

**Comment by SurajPrakash24** [comment]
Can You plz assign it to me.

**Comment by Coding-Phase** [comment]
Hello! I'm interested in taking on this task, so could you please assign it to me?

**Comment by vkumar8192449** [comment]
i want to work on it 😁
